sudo: required

language: generic

git:
  depth: false

services:
  - docker

before_install:
  - docker pull moussavdb/build-java

script:
  - chmod 777 deploy-maven-central.sh
  - docker run -v $PWD:/src -w /src moussavdb/build-java ./deploy-maven-central.sh
