sudo: required

language: generic

git:
  depth: false

services:
  - docker

before_install:
  - docker pull moussavdb/build-java

script:
  - docker run -v $PWD:/src -w /src moussavdb/build-java openssl aes-256-cbc -pass pass:$OPENSSL_PWD -in private-key.gpg.enc -out private-key.gpg -d
  - docker run -v $PWD:/src -w /src moussavdb/build-java gpg --import --batch private-key.gpg
  - docker run -v $PWD:/src -w /src moussavdb/build-java mvn -V -s settings.xml org.jacoco:jacoco-maven-plugin:prepare-agent clean deploy sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR
